### ISSUE TITLE
Are the Baskin Robbins 31 flavors included? 

### ISSUE THREAD

**Issue by chipmonkey** [TwoScoopGames/ScoopChain#5]
Certainly classic flavors. Perhaps a "BR" prefix?

**Comment by AlexBezuska** [comment]
Yeah we need those! I gotta find a list, even the retired ones I pet there is are a ton.

I've had a hard time deciding on including company names. 

I can go a couple of ways:
- Include company names
- Only include local Louisville area company names
- Not include any company names

I feel like right now I am leaning towards only local Lou company names because it will be a fun easter egg for locals, and something to intice non-locals; "Wow this one must be good if it's so specific and regional!" thus upping Lousivlle tourism and boosting the economy! ... hahaha

Thoughts?

**Comment by chipmonkey** [comment]
I wondered if you wanted to be local-only; Graeters started in Cincinnati, but that's fairly close.  Baskin Robbins has just been around so long in Louisville (and everywhere) I thought I'd include it.  Oooh, I need to go add Ehrler's.

I like the company names for some flavors, but there's no point in having "Vanilla" four times.  But for anything company specific it might be nice.  We can see how the data shakes out.

**Comment by chipmonkey** [comment]
See #7

**Comment by AlexBezuska** [comment]
I like your format with "flavor (company name)" I think that's the way to go from here on out. I think company name might be a good idea because from talking to a few people it seems like they really like the specificity of company x's flavor.
